export const blacklist: Record<string, boolean> = {
    '/SbisEnvUI-demo/app/SbisEnvUI-demo%2FList%2FList': true,
    '/SbisEnvUI-demo/app/SbisEnvUI-demo/List/List': true,
    '/DemoStand/app/Engine-demo%2FSiteEditorBase%2FFrameEditorAutotests%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FDashboard%2FPage%2FPage': true,
    '/DemoStand/app/Engine-demo%2FTextEditor%2FExtended%2FEditor': true,
    '/DemoStand/app/Engine-demo%2FNewViewConfiguration%2FIndex': true,
    '/page/dashboards': true,
    '/page/settings_monitoring_main': true,
    '/SchemeEditor-demo/app/SchemeEditor-demo%2FBase%2FBase': true,
    '/UIDemo/app/CompatibleDemo%2FWasabyEnv%2FMixed%2FMixed': true,
    '/SbisEnvUI-demo/SbisEnvUI/Pages/500': true,
    '/page/main-layout-max-width': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FButton%2FHistoryId%2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FButton%2FMaxHistoryVisibleItems%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FDocsEditor%2FView': true,
    '/DemoStand/app/Engine-demo%2FModuleEditor%2FView%2FView': true,
    '/page/empty-page': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FStoreIdConnected%2FIndex': true,
    '/DemoStand/app/Controls-Calculator-demo%2FCalculator': true,
    '/DemoStand/app/Engine-demo%2FGraphs%2Fautotests%2FInfoBlock': true,
    '/DemoStand/app/Engine-demo%2FHeaders%2FLayout%2FBackground%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FHeaders%2FLayout': true,
    '/DemoStand/app/Engine-demo%2FHeaders%2FContentPanel%2FInlineMainText%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FHeaders%2FZen%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FHeaders%2FLayout%2FBase%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FLanguageInput%2FName%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FLanguageInput%2FMultilineName%2FIndex': true,
    '/SbisEnvUI-demo/app/SbisEnvUI-demo%2FError%2FRouting%2FTest': true,
    '/SbisEnvUI-demo/app/SbisEnvUI-demo/Error/Routing/Test': true,
    '/Engine-demo/app/Engine-demo%2FDocsEditor%2FView': true,
    '/DemoStand/app/HelpBase-demo%2FRoutes%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FEngineLanguage%2FSelectorNew': true,
    '/DemoStand/app/Engine-demo%2FLinkDecorator%2FEditor%2FEditor': true,
    '/page': true,
    '/DemoStand/app/Engine-demo%2FStylesConfiguration%2FDemo': true,
    '/DemoStand/app/Engine-demo%2FTextEditor%2FHistory%2FEditor': true,
    '/Engine-demo/app/Engine-demo%2FTOC%2FView': true,
    '/DemoStand/app/Engine-demo%2FEngineUser%2FUserButtonNew': true,
    '/DemoStand/app/Engine-demo%2FControls-widgets%2FExpandedCompositeTree%2FCentered%2FIndex':
        true,
    '/DemoStand/app/NavigationPanels-demo%2FScrollViewer%2FIntegration%2FBase%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FLongOperations%2FDemo': true,
    '/DemoStand/app/Engine-demo%2FExport%2FDemo': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FView%2FAlignment%2FIndex': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FView%2FViewMode%2FBasic%2FIndex': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FView%2FViewMode%2FExtended%2FIndex': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FView%2FEditors%2FIndex': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FView%2FDetailPanelExtendedItemsViewMode%2FIndex':
        true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FView%2FEditors%2FBooleanEditor%2FIndex': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilterPanelPopup%2FSticky%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FConnectedByBrowser%2FIndex': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FView%2FEditors%2FDateMenuEditor%2FIndex': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFrequentFilter%2FTumbler%2FIndex': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FView%2FEditors%2FDropdownEditor%2FIndex': true,
    '/Engine-demo/app/Engine-demo%2FBottomBarPG': true,
    '/DemoStand/app/NoticeCenter-demo%2FNoticeSettingsAccountPage%2FIndex': true,
    '/page/hint-routes': true,
    '/DemoStand/app/NoticeCenter-demo%2FNoticeCenter%2FDemo': true,
    '/page/editor_card_click': true,
    '/page/main-page': true,
    '/custom_service_root/group/123-456/page/main-page': true,
    '/custom_service_root/page/main-page': true,
    '/page/sale-script-scheme': true,
    '/page/master-group-item-1': true,
    '/page/settings_monitoring_security': true,
    '/page/rights-master-forbidden': true,
    '/page/data_base': true,
    '/page/tasks_on_me': true,
    '/page/card-registry': true,
    '/': true,
    '/page/settings_1': true,
    '/page/card-layout-max-width': true,
    '/page/header-page': true,
    '/group/id/page/feature-catalog': true,
    '/group/id/page/settings_1': true,
    '/page/settings_system_notification': true,
    '/page/filter-position-left': true,
    '/page/filter-position-right-top': true,
    '/page/master-folder-page-3': true,
    '/page/empty-view': true,
    '/DemoStand/app/Controls-demo%2FButtons%2FButtonStyle%2FIndex': true,
    '/DemoStand/app/Controls-Deprecated-demo%2FPopup%2FCompatible%2FTestCompoundAreaForOldTpl':
        true,
    '/DemoStand/app/Controls-demo%2FSlider%2FRange%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FSlider%2FBase%2FmarkerVisibility%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FSlider%2FRange%2FScaleStep%2FIndex': true,
    '/DemoStand/app/Controls-Templates-demo%2FBackgroundItem%2FIndex': true,
    '/DemoStand/app/Controls-Templates-demo%2FHorizontalItem%2FIndex': true,
    '/DemoStand/app/Controls-Templates-demo%2FListItem%2FIndex': true,
    '/DemoStand/app/Controls-Templates-demo%2FVerticalItem%2FImagePosition%2FIndex': true,
    '/DemoStand/app/Controls-Lists-demo%2FdynamicGrid%2Fbase%2FIndex': true,
    '/DemoStand/app/Controls-Lists-demo%2FdynamicGrid%2Fhover%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FFingers%2FBase%2FIndex': true,
    '/DemoStand/app/Controls-demo%2Flist_new%2FDragNDrop%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FEditInPlace%2FExcel%2FStartColumnIndex%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FEditInPlace%2FSingleCellEditable%2FIndex': true,
    '/DemoStand/app/Controls-demo%2Flist_new%2FEditInPlace%2FAddItem%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FEditInPlace%2FEditingOnMounting%2FIndex': true,
    '/DemoStand/app/Controls-demo%2Flist_new%2FEditInPlace%2FAutoAddOnMount%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FEditInPlace%2FValidation%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FEditInPlace%2FEditingCell%2FIndex': true,
    '/DemoStand/app/Controls-demo%2Flist_new%2FEditInPlace%2FAutoAdd%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FColumnScroll%2FEditOnAfterMount%2FIndex': true,
    '/DemoStand/app/Controls-demo%2Flist_new%2FItemClick%2FWithEditing%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FtreeGridNew%2FExpander%2FIntegration%2FExpanderIcon%2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2FtileNew%2FDifferentItemTemplates%2FRichTemplate%2FCharacteristics%2FIndex':
        true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilterPanel%2FView%2FViewMode%2FIndex': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FView%2FDetailPanelExtendedTemplateName%2FIndex':
        true,
    '/DemoStand/app/Controls-ListEnv-demo%2FOperationsConnected%2FMultiSelectorCheckbox%2FIndex':
        true,
    '/DemoStand/app/Controls-ListEnv-demo%2FOperationsConnected%2FSimpleMultiSelector%2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2FPropertyGridEditor%2FItemActions%2FItemActions%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FPropertyGridEditor%2FItemActions%2FItemActionVisibilityCallback%2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2FInput%2FDropdown%2FDropdown': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FReadOnly%2FIndex': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilterPanel%2FView%2FEditors%2FDateRangeEditor%2FIndex':
        true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilterPanel%2FView%2FEditors%2FDateEditor%2FIndex':
        true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilterPanelPopup%2FSticky%2FHistoryId%2FFavoriteDialog%2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2FFilterOld%2FFilterView%2FSource%2FAdditionalTemplateProperty%2FIndex':
        true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FView%2FEditors%2FLookupEditor%2FBase%2FIndex':
        true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilterPanel%2FView%2FExpanderVisible%2FIndex': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FNotConnectedView%2FRichDemo%2FIndex': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FView%2FFilterVisibilityCallback%2FIndex': true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FView%2FFilterChangedCallback%2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FSearch%2FHistoryId%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FPropertyGridNew%2FEditors%2FIndex': true,
    '/UIDemo/app/Production%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FShortDatePicker%2FSource%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FShortDatePicker%2FChooseQuarters%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FShortDatePicker%2FMonthTemplateDoc%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FExtControls%2FGlobalFloatingToolbar%2FIndex': true,

    // new errors
    '/DemoStand/app/HintManager-demo%2FPlayer%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FPageInfo%2FPage': true,
    '/DemoStand/app/Engine-demo%2FRichEditor%2FPG%2FExtended%2FEditor': true,
    '/DemoStand/app/Controls-Lists-editors-demo%2FColumnEditor%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FControls-widgets%2FNewBrowser%2FCharacteristics%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FViewConfiguration%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FBrowser%2FOperationsPanel%2FDemo': true,
    '/DemoStand/app/Engine-demo%2FBrowser': true,
    '/DemoStand/app/Engine-demo%2FImport%2FTemplatesList%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FImport%2FButton%2FDefaultTemplates%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FImport%2FImportTemplates%2FCreateAndEdit%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FImport%2FDefaultTemplates%2FIndex': true,
    '/DemoStand/app/Engine-demo%2FReport%2FOpener': true,
    '/DemoStand/app/ImageEditor2-demo%2FPage': true,
    '/DemoStand/app/ImageEditor2-demo%2FSync': true,
    '/DemoStand/app/NavigationPanels-demo%2Faccordion%2FDemo': true,
    '/DemoStand/app/NoticeCenter-demo%2FNoticeSettingsClientPage%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FInput%2FPhone%2FBase%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FInput%2FPhone%2FFlagPosition%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FInput%2FPhone%2FFlagVisible%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FTabs%2FAdaptiveButtons%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FTabs%2FAdaptiveButtons%2FMoreButtonAlign%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FTabs%2FAdaptiveButtons%2FTemplateType%2FIndex': true,
    '/DemoStand/app/Controls-Lists-demo%2FtimelineGrid%2FDev%2FScale': true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FSorting%2FSortingSelector%2FDefault%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FSorting%2FSortingSelector%2FIconStyle%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FSorting%2FSortingSelector%2FIconSize%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FSorting%2FSortingSelector%2FFontColorStyle%2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FSorting%2FSortingSelector%2FSortingSelectorWithReset%2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FSorting%2FSortingSelector%2FSortingSelectorWithHeader%2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FSorting%2FSortingSelector%2FIcons%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FSorting%2FSortingSelector%2FArrowTitle%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FSorting%2FSortingSelector%2FIconsSvg%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FgridNew%2FSorting%2FSortingSelector%2FViewMode%2FIndex': true,
    '/DemoStand/app/Controls-demo%2Flist_new%2FNavigation%2FDigitPaging%2FIndex': true,
    '/DemoStand/app/Controls-demo%2Flist_new%2FNavigation%2FDigitPaging%2FWithScroll%2FIndex': true,
    '/DemoStand/app/Controls-demo%2FObjectTypeEditor%2FBaseEditorsPopup%2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FContentTemplate%2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FItemTemplate%2FContentTemplate%2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FSearch%2FSearchParam%2FFlatList%2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FFooterContentTemplate%2FSimple%2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FFooterContentTemplate%2FOneItem%2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FMultiSelect%2FSimple%2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FMultiSelect%2FPinnedItems%2FSimple%2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FItemTemplate%2FAdditionalTextTemplate%2FMultiSelect%2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FMaxVisibleItems2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FMultiSelect%2FPinnedItems2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FFontSize2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FFontColorStyle2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FGroupProperty%2FSimple2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FGroupProperty%2FGroupTemplate2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FParentProperty2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FEmptyText%2FSimple2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FScroll2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FValidationStatus2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FSelectedAllText%2FSimple2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FItemTemplateProperty2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FNodeProperty2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FUnderline2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FSearch%2FSearchParam%2FHierarchyList2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FSource%2FSimple2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FSource%2FIconSize2FIndex': true,
    '/DemoStand/app/Controls-demo%2FFilterOld%2FFilterPopup%2FEditDialog2FIndex': true,
    '/DemoStand/app/Controls-demo%2FFilterOld%2FFilterPopup%2FDetailPanel%2FScroll2FIndex': true,
    '/DemoStand/app/Controls-demo%2FFilterOld%2FFilterPopup%2FDetailPanel%2FHiddenItem2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2FFilterOld%2FFilterPopup%2FDetailPanel%2FHistoryId%2FDefault2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2FFilterOld%2FFilterPopup%2FDetailPanel%2FHistoryId%2FManyItems2FIndex':
        true,
    '/DemoStand/app/Controls-ListEnv-demo%2FFilter%2FNotConnectedView%2FEmptyText2FIndex': true,
    '/DemoStand/app/Controls-demo%2FFilterOld%2FPanelVDom%2FPanelVDom': true,
    '/DemoStand/app/Controls-demo%2FFilterOld%2FFilterPopup%2FDetailPanel%2FHistoryId2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FMultiSelect%2FNavigationAndSelectorTemplate2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FMultiSelect%2FMultiSelectAccessibilityProperty2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FSource2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FEmptyText2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FMenuHeadingCaption2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FItemActions2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FItemTemplate%2FAdditionalTextTemplate%2FSimple2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FMultiSelect%2FHierarchy2FIndex': true,
    '/DemoStand/app/Controls-demo%2Fdropdown_new%2FInput%2FMultiSelect%2FBeforeSelectionChangedCallback2FIndex':
        true,
    '/DemoStand/app/Controls-demo%2FPropertyGridNew%2FEditors%2FLogic2FIndex': true,
    '/DemoStand/app/Controls-demo%2FFilterOld%2FFilterSearch%2FFilterSearch': true,

    // то что не падает в ветке. вероятно из-за информеров или еще чего-то, что вылезает только в rc
    //'/page': true,
    '/page/before-tabs-master-1': true,
    //'/custom_service_root/group/123-456/page/main-page': true,
    //'/page/sale-script-scheme': true,
    '/page/application-open': true,
    '/page/settings_default_handler': true,
    '/page/extensions-check': true,
    //'/page/rights-master-forbidden': true,
    '/page/static-title-page': true,
    '/page/master-config-no-navigation-page': true,
    '/page/settings_license': true,
    '/page/title-from-query': true,
    '/page/card-layout-page-1': true,
    '/page/block-bottom-1': true,
    '/page/error-ie-title-empty': true,
    '/page/settings_monitoring_on_content-long': true,
    '/page/settings_long_title_sub': true,
    '/page/demo-card-stack': true,
    '/page/toolbar-page-2': true,
    '/page/block-4': true,
    '/page/multi-editing-second': true,
    //'/page/tasks_on_me': true,
    '/page/blocks': true,
    '/page/blocks-2': true,
    '/SabyPage-demo/page/settings_system_notification': true,
    '/SabyPage-demo/page/settings_monitoring_main': true,
    '/page/settings_monitoring_main/': true,
    '/page/filter-position-left-tabs': true,
    '/page/filter-position-right': true,
    //'/page/master-folder-page-3': true,
    '/page/create-entity-2': true,
    '/page/multi-editing-third': true,
    '/page/group-page-1': true,
    '/project/213/page/group-page-1': true,
    '/page/settings_2': true,
    '/group/id/page/editor_list_click': true,
    '/group/id/page/settings_license': true,
    '/group/id/page/dynamic-title-page': true,
    //'/page/settings_1': true,
    '/page/navigate-1': true,
    '/page/navigate-2': true,
    '/page/toolbar-page-1': true,
    '/page/frame-preview-opener': true,

    // а это редиректящие страницы, видимо их тоже надо учесть

    //'/page/before-tabs-master-1': true,
    //'/page/main-page': true,
    '/page/sale-scripts': true,
    //'/page/application-open': true,
    //'/page/settings_default_handler': true,
    //'/page/extensions-check': true,
    '/page/rights-forbidden': true,
    //'/page/static-title-page': true,
    '/page/master-config-page': true,
    //'/page/settings_license': true,
    //'/page/title-from-query': true,
    //'/page/card-layout-page-1': true,
    //'/page/block-bottom-1': true,
    //'/page/error-ie-title-empty': true,
    //'/page/settings_monitoring_on_content-long': true,
    //'/page/settings_long_title_sub': true,
    //'/page/demo-card-stack': true,
    //'/page/toolbar-page-2': true,
    //'/page/block-4': true,
    '/page/multi-editing-first': true,
    '/page/block-2': true,
    '/page/block-bottom-2': true,
    //'/page/settings_system_notification': true,
    //'/page/settings_monitoring_main': true,
    '/page/test-page-redirect': true,
    //'/page/filter-position-left-tabs': true,
    //'/page/filter-position-right': true,
    '/page/master-folder-page-2': true,
    '/page/create-entity': true,
    //'/page/group-page-1': true,
    //'/page/settings_2': true,
    '/page/editor_list_click': true,
    '/page/dynamic-title-page': true,
    '/page/settings_monitoring_ui': true,
    //'/page/navigate-1': true,
    //'/page/toolbar-page-1': true,

    // еще одну демку сломали
    '/FrameDemoStand': true,

    // нестабильный тест, вроде после нескольких перезагрузок повторяется
    '/UIDemo/app/AsyncDemo%2FIndex': true,

    // почему-то нестабильные тесты в rc, после нескольких перезапусков прошли. а именно
    // page/empty-master?emptyTemplates=true&emptyNotice=true&noticeDashboard=true
    // page/empty-dashboard?emptyTemplates=true&emptyNotice=true&frame=...
    // page/empty-default?emptyTemplates=true&emptyNotice=true&noticeDashboard=true
    // DemoStand/app/Engine-demo%2FIP%2FIndex
    '/DemoStand/app/Engine-demo%2FIP%2FIndex': true,
    '/page/empty-default': true,
    '/page/empty-dashboard': true,
    '/page/empty-master': true,
};
