export const blacklist: Record<string, boolean> = {
    '/page/header-page': true,
    '/DemoStand/app/Controls-Calculator-demo/Calculator': true,
    '/DemoStand/app/Engine-demo/SiteEditorBase/FrameEditorAutotests/Index': true,
    '/DemoStand/app/Engine-demo/ModuleEditor/View/View': true,
    '/DemoStand/app/HelpBase-demo/Routes/Index': true,
    '/page/frame-preview-opener': true,
    '/page/dashboards': true,
    '/Engine-demo/app/Engine-demo/BottomBarPG': true,
    '/page/main-page': true,
    '/custom_service_root/page/main-page': true,
    '/SabyPage-demo/page/settings_system_notification': true,
    '/SchemeEditor-demo/app/SchemeEditor-demo/Base/Base': true,
    '/DemoStand/app/Controls-Deprecated-demo/Popup/Compatible/TestCompoundAreaForOldTpl': true,
    '/UIDemo/app/Production/Index': true,
    '/UIDemo/app/AsyncDemo/Index': true,

    // то что не падает в ветке. вероятно из-за информеров или еще чего-то, что вылезает только в rc
    '/page/before-tabs-master-1': true,
    '/page/extensions-check': true,
    '/page/static-title-page': true,
    '/page/master-config-no-navigation-page': true,
    '/page/settings_license': true,
    '/page/card-layout-page-1': true,
    '/page/block-bottom-1': true,
    '/page/error-ie-title-empty': true,
    '/page/settings_monitoring_on_content-long': true,
    '/page/settings_long_title_sub': true,
    '/page/demo-card-stack': true,
    '/page/toolbar-page-2': true,
    '/page/block-4': true,
    '/page/blocks': true,
    '/page/blocks-2': true,
    '/SabyPage-demo/page/settings_monitoring_main': true,
    '/page/settings_monitoring_main': true,
    '/page/filter-position-left-tabs': true,
    '/page/filter-position-right': true,
    '/page/create-entity-2': true,
    '/page/group-page-1': true,
    '/project/213/page/group-page-1': true,
    '/group/id/page/settings_license': true,
    '/page/navigate-1': true,
    '/page/navigate-2': true,
    '/page/toolbar-page-1': true,

    // а это редиректящие страницы, видимо их тоже надо учесть

    '/page/sale-scripts': true,
    '/page/rights-forbidden': true,
    '/page/multi-editing-first': true,
    '/page/block-2': true,
    '/page/block-bottom-2': true,
    '/page/test-page-redirect': true,
    '/page/master-folder-page-2': true,
    '/page/create-entity': true,
    '/page/editor_list_click': true,
    '/page/dynamic-title-page': true,
    '/page/settings_monitoring_ui': true,

    // еще одну демку сломали
    '/FrameDemoStand': true,

    // почему-то нестабильные тесты в rc, после нескольких перезапусков прошли. а именно
    '/DemoStand/app/Engine-demo/IP/Index': true,
    '/page/empty-default': true,
    '/page/empty-dashboard': true,
    '/page/empty-master': true,
};
