export const blacklist: Record<string, boolean> = {
    '/SbisEnvUI-demo/app/SbisEnvUI-demo/List/List': true,
    '/SbisEnvUI-demo/app/SbisEnvUI-demo/Error/Routing/Test': true,
    '/SbisEnvUI-demo/SbisEnvUI/Pages/500': true,
    '/page/dashboards/': true,
    '/page/frame-preview-opener': true,
    '/page/': true,
    '/page/dashboards': true,
    '/Engine-demo/app/Engine-demo/BottomBarPG': true,
    '/page/empty-page': true,
    '/page/hint-routes': true,
    '/page/settings_2': true,
    '/page/rights-master-forbidden': true,
    '/group/123-456/page/settings_monitoring_main': true,
    '/custom_service_root/group/123-456/page/main-page': true,
    '/page/settings_default_handler': true,
    '/page/master-config-page': true,
    '/page/title-from-query': true,
    '/page/main-page': true,
    '/page/settings_1': true,
    '/page/settings_monitoring_main': true,
    '/page/application-open': true,
    '/page/multi-editing-second': true,
    '/page/header-page': true,
    '/group/id/page/editor_list_click': true,
    '/group/id/page/settings_1': true,
    '/SabyPage-demo/page/settings_system_notification': true,
    '/page/settings_system_notification': true,
    '/page/multi-editing-third': true,
    '/group/id/page/dynamic-title-page': true,
    '/SchemeEditor-demo/app/SchemeEditor-demo/Base/Base': true,
    '/UIDemo/app/CompatibleDemo/WasabyEnv/Mixed/Mixed': true,
    '/UIDemo/app/Production/Index': true,
    '/UIDemo/app/AsyncDemo/Index': true,
    '/DemoStand/app/Controls-Calculator-demo/Calculator': true,
    '/DemoStand/app/Engine-demo/Graphs/autotests/InfoBlock': true,
    '/DemoStand/app/Engine-demo/Headers/Layout/Background/Index': true,
    '/DemoStand/app/Engine-demo/Headers/Layout': true,
    '/DemoStand/app/Engine-demo/Headers/ContentPanel/InlineMainText/Index': true,
    '/DemoStand/app/Engine-demo/Headers/Zen/Index': true,
    '/DemoStand/app/Engine-demo/Headers/Layout/Base/Index': true,
    '/DemoStand/app/Engine-demo/SiteEditorBase/FrameEditorAutotests/Index': true,
    '/DemoStand/app/Engine-demo/ModuleEditor/View/View': true,
    '/DemoStand/app/HelpBase-demo/Routes/Index': true,
    '/DemoStand/app/HintManager-demo/Player/Index': true,
    '/DemoStand/app/Engine-demo/TextEditor/Extended/Editor': true,
    '/DemoStand/app/Engine-demo/LinkDecorator/Editor/Editor': true,
    '/DemoStand/app/Engine-demo/Dashboard/Page/Page': true,
    '/DemoStand/app/Engine-demo/StylesConfiguration/Demo': true,
    '/DemoStand/app/Engine-demo/TextEditor/History/Editor': true,
    '/DemoStand/app/Engine-demo/Controls-widgets/ExpandedCompositeTree/Centered/Index': true,
    '/DemoStand/app/NavigationPanels-demo/ScrollViewer/Integration/Base/Index': true,
    '/DemoStand/app/Engine-demo/LongOperations/Demo': true,
    '/DemoStand/app/Engine-demo/Export/Demo': true,
    '/DemoStand/app/Controls-ListEnv-demo/StoreIdConnected/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/View/Alignment/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/View/ViewMode/Basic/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/View/ViewMode/Extended/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/View/Editors/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/View/DetailPanelExtendedItemsViewMode/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/View/Editors/BooleanEditor/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/FilterPanelPopup/Sticky/Index': true,
    '/DemoStand/app/Controls-demo/ConnectedByBrowser/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/View/Editors/DateMenuEditor/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/FrequentFilter/Tumbler/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/View/Editors/DropdownEditor/Index': true,
    '/DemoStand/app/NoticeCenter-demo/NoticeSettingsClientPage/Index': true,
    '/DemoStand/app/Controls-Deprecated-demo/Popup/Compatible/TestCompoundAreaForOldTpl': true,
    '/DemoStand/app/Controls-demo/ShortDatePicker/Source/Index': true,
    '/DemoStand/app/Controls-demo/Slider/Range/Index': true,
    '/DemoStand/app/Controls-demo/Slider/Base/markerVisibility/Index': true,
    '/DemoStand/app/Controls-demo/Slider/Range/ScaleStep/Index': true,
    '/DemoStand/app/Controls-Templates-demo/BackgroundItem/Index': true,
    '/DemoStand/app/Controls-Templates-demo/HorizontalItem/Index': true,
    '/DemoStand/app/Controls-Templates-demo/ListItem/Index': true,
    '/DemoStand/app/Controls-Templates-demo/VerticalItem/ImagePosition/Index': true,
    '/DemoStand/app/Controls-demo/Fingers/Base/Index': true,
    '/DemoStand/app/Controls-demo/treeGridNew/Expander/Integration/ExpanderIcon/Index': true,
    '/DemoStand/app/Controls-demo/tileNew/DifferentItemTemplates/RichTemplate/Characteristics/Index':
        true,
    '/DemoStand/app/Controls-ListEnv-demo/FilterPanel/View/ViewMode/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/View/DetailPanelExtendedTemplateName/Index': true,
    '/DemoStand/app/Controls-demo/PropertyGridEditor/ItemActions/ItemActions/Index': true,
    '/DemoStand/app/Controls-demo/PropertyGridEditor/ItemActions/ItemActionVisibilityCallback/Index':
        true,
    '/DemoStand/app/Controls-demo/dropdown_new/Button/HistoryId/Index': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Button/MaxHistoryVisibleItems/Index': true,
    '/DemoStand/app/Controls-demo/Input/Dropdown/Dropdown': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/ReadOnly/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/FilterPanel/View/Editors/DateRangeEditor/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/FilterPanel/View/Editors/DateEditor/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/FilterPanelPopup/Sticky/HistoryId/FavoriteDialog/Index':
        true,
    '/DemoStand/app/Controls-demo/FilterOld/FilterView/Source/AdditionalTemplateProperty/Index':
        true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/View/Editors/LookupEditor/Base/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/FilterPanel/View/ExpanderVisible/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/NotConnectedView/RichDemo/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/View/FilterVisibilityCallback/Index': true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/View/FilterChangedCallback/Index': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Search/HistoryId/Index': true,
    '/DemoStand/app/Controls-demo/PropertyGridNew/Editors/Index': true,

    // new errors
    '/DemoStand/app/Engine-demo/PageInfo/Page': true,
    '/DemoStand/app/Engine-demo/RichEditor/PG/Extended/Editor': true,
    '/DemoStand/app/Controls-Lists-editors-demo/ColumnEditor/Index': true,
    '/DemoStand/app/Engine-demo/Controls-widgets/NewBrowser/Characteristics/Index': true,
    '/DemoStand/app/Engine-demo/ViewConfiguration/Index': true,
    '/DemoStand/app/Engine-demo/Browser/OperationsPanel/Demo': true,
    '/DemoStand/app/Engine-demo/Browser': true,
    '/DemoStand/app/Engine-demo/Import/TemplatesList/Index': true,
    '/DemoStand/app/Engine-demo/Import/Button/DefaultTemplates/Index': true,
    '/DemoStand/app/Engine-demo/Import/ImportTemplates/CreateAndEdit/Index': true,
    '/DemoStand/app/Engine-demo/Import/DefaultTemplates/Index': true,
    '/DemoStand/app/Engine-demo/Report/Opener': true,
    '/DemoStand/app/ImageEditor2-demo/Page': true,
    '/DemoStand/app/ImageEditor2-demo/Sync': true,
    '/DemoStand/app/NavigationPanels-demo/accordion/Demo': true,
    '/DemoStand/app/Controls-demo/Input/Phone/Base/Index': true,
    '/DemoStand/app/Controls-demo/Input/Phone/FlagPosition/Index': true,
    '/DemoStand/app/Controls-demo/Input/Phone/FlagVisible/Index': true,
    '/DemoStand/app/Controls-demo/Tabs/AdaptiveButtons/Index': true,
    '/DemoStand/app/Controls-demo/Tabs/AdaptiveButtons/MoreButtonAlign/Index': true,
    '/DemoStand/app/Controls-demo/Tabs/AdaptiveButtons/TemplateType/Index': true,
    '/DemoStand/app/Controls-Lists-demo/timelineGrid/Dev/Scale': true,
    '/DemoStand/app/Controls-demo/gridNew/Sorting/SortingSelector/Default/Index': true,
    '/DemoStand/app/Controls-demo/gridNew/Sorting/SortingSelector/IconStyle/Index': true,
    '/DemoStand/app/Controls-demo/gridNew/Sorting/SortingSelector/IconSize/Index': true,
    '/DemoStand/app/Controls-demo/gridNew/Sorting/SortingSelector/FontColorStyle/Index': true,
    '/DemoStand/app/Controls-demo/gridNew/Sorting/SortingSelector/SortingSelectorWithReset/Index':
        true,
    '/DemoStand/app/Controls-demo/gridNew/Sorting/SortingSelector/SortingSelectorWithHeader/Index':
        true,
    '/DemoStand/app/Controls-demo/gridNew/Sorting/SortingSelector/Icons/Index': true,
    '/DemoStand/app/Controls-demo/gridNew/Sorting/SortingSelector/ArrowTitle/Index': true,
    '/DemoStand/app/Controls-demo/gridNew/Sorting/SortingSelector/IconsSvg/Index': true,
    '/DemoStand/app/Controls-demo/gridNew/Sorting/SortingSelector/ViewMode/Index': true,
    '/DemoStand/app/Controls-demo/list_new/Navigation/DigitPaging/Index': true,
    '/DemoStand/app/Controls-demo/list_new/Navigation/DigitPaging/WithScroll/Index': true,
    '/DemoStand/app/Controls-demo/ObjectTypeEditor/BaseEditorsPopup/Index': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/ContentTemplate/Index': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/ItemTemplate/ContentTemplate/Index': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Search/SearchParam/FlatList/Index': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/FooterContentTemplate/Simple/Index': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/FooterContentTemplate/OneItem/Index': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/MultiSelect/Simple/Index': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/MultiSelect/PinnedItems/Simple/Index': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/ItemTemplate/AdditionalTextTemplate/MultiSelect/Index':
        true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/MaxVisibleItems2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/MultiSelect/PinnedItems2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/FontSize2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/FontColorStyle2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/GroupProperty/Simple2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/GroupProperty/GroupTemplate2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/ParentProperty2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/EmptyText/Simple2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/Scroll2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/ValidationStatus2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/SelectedAllText/Simple2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/ItemTemplateProperty2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/NodeProperty2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/Underline2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Search/SearchParam/HierarchyList2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/Source/Simple2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/Source/IconSize2FIndex': true,
    '/DemoStand/app/Controls-demo/FilterOld/FilterPopup/EditDialog2FIndex': true,
    '/DemoStand/app/Controls-demo/FilterOld/FilterPopup/DetailPanel/Scroll2FIndex': true,
    '/DemoStand/app/Controls-demo/FilterOld/FilterPopup/DetailPanel/HiddenItem2FIndex': true,
    '/DemoStand/app/Controls-demo/FilterOld/FilterPopup/DetailPanel/HistoryId/Default2FIndex': true,
    '/DemoStand/app/Controls-demo/FilterOld/FilterPopup/DetailPanel/HistoryId/ManyItems2FIndex':
        true,
    '/DemoStand/app/Controls-ListEnv-demo/Filter/NotConnectedView/EmptyText2FIndex': true,
    '/DemoStand/app/Controls-demo/FilterOld/PanelVDom/PanelVDom': true,
    '/DemoStand/app/Controls-demo/FilterOld/FilterPopup/DetailPanel/HistoryId2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/MultiSelect/NavigationAndSelectorTemplate2FIndex':
        true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/MultiSelect/MultiSelectAccessibilityProperty2FIndex':
        true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/Source2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/EmptyText2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/MenuHeadingCaption2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/ItemActions2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/ItemTemplate/AdditionalTextTemplate/Simple2FIndex':
        true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/MultiSelect/Hierarchy2FIndex': true,
    '/DemoStand/app/Controls-demo/dropdown_new/Input/MultiSelect/BeforeSelectionChangedCallback2FIndex':
        true,
    '/DemoStand/app/Controls-demo/PropertyGridNew/Editors/Logic2FIndex': true,
    '/DemoStand/app/Controls-demo/FilterOld/FilterSearch/FilterSearch': true,

    // то что не падает в ветке. вероятно из-за информеров или еще чего-то, что вылезает только в rc
    '/page/before-tabs-master-1': true,
    '/page/extensions-check': true,
    '/page/static-title-page': true,
    '/page/master-config-no-navigation-page': true,
    '/page/settings_license': true,
    '/page/card-layout-page-1': true,
    '/page/block-bottom-1': true,
    '/page/error-ie-title-empty': true,
    '/page/settings_monitoring_on_content-long': true,
    '/page/settings_long_title_sub': true,
    '/page/demo-card-stack': true,
    '/page/toolbar-page-2': true,
    '/page/block-4': true,
    '/page/blocks': true,
    '/page/blocks-2': true,
    '/SabyPage-demo/page/settings_monitoring_main': true,
    '/page/settings_monitoring_main/': true,
    '/page/filter-position-left-tabs': true,
    '/page/filter-position-right': true,
    '/page/create-entity-2': true,
    '/page/group-page-1': true,
    '/project/213/page/group-page-1': true,
    '/group/id/page/settings_license': true,
    '/page/navigate-1': true,
    '/page/navigate-2': true,
    '/page/toolbar-page-1': true,

    // а это редиректящие страницы, видимо их тоже надо учесть

    '/page/sale-scripts': true,
    '/page/rights-forbidden': true,
    '/page/multi-editing-first': true,
    '/page/block-2': true,
    '/page/block-bottom-2': true,
    '/page/test-page-redirect': true,
    '/page/master-folder-page-2': true,
    '/page/create-entity': true,
    '/page/editor_list_click': true,
    '/page/dynamic-title-page': true,
    '/page/settings_monitoring_ui': true,

    // еще одну демку сломали
    '/FrameDemoStand': true,

    // почему-то нестабильные тесты в rc, после нескольких перезапусков прошли. а именно
    '/DemoStand/app/Engine-demo/IP/Index': true,
    '/page/empty-default': true,
    '/page/empty-dashboard': true,
    '/page/empty-master': true,
};
